# permissions for end users to view chartpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: webhookmix
    app.kubernetes.io/managed-by: kustomize
  name: chartpreset-viewer-role
rules:
- apiGroups:
  - charts.kubedb.dev
  resources:
  - chartpresets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.kubedb.dev
  resources:
  - chartpresets/status
  verbs:
  - get
