---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - charts.kubedb.dev
  resources:
  - chartpresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.kubedb.dev
  resources:
  - chartpresets/finalizers
  verbs:
  - update
- apiGroups:
  - charts.kubedb.dev
  resources:
  - chartpresets/status
  verbs:
  - get
  - patch
  - update
